name: Build Redis DIY

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Version'
        required: true
        default: "6.2.13"
        type: string
      make_latest:
        description: 'Latest'
        default: false
        type: boolean

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download source code
        run: |
          $tag_name="${{ inputs.tag_name }}"
          (ConvertFrom-Json(Invoke-WebRequest -Headers @{'Authorization' = 'Bearer ${{ secrets.GITHUB_TOKEN }}'} -Uri "https://api.github.com/repos/redis/redis/releases/tags/$($tag_name.Trim())").Content).body -Replace '\(\#', '(https://github.com/redis/redis/pull/' | Set-Content .\redis_latest_body.txt
          Invoke-WebRequest -Uri https://github.com/redis/redis/archive/refs/tags/$($tag_name.Trim()).tar.gz -OutFile redis-$($tag_name.Trim()).tar.gz
          Add-Content -Path $env:GITHUB_ENV -Value "RELEASE_VERSION=$($tag_name.Trim())"
          Add-Content -Path $env:GITHUB_ENV -Value "REDIS_DIST=Redis-$($tag_name.Trim())-Windows-x64"

      - name: Setup MinGW-w64
        run: |
          choco install -y mingw
          echo "::add-path::C:\\tools\\mingw64\\bin"

      - name: Build Redis with MinGW-w64
        run: |
          tar -xzf redis-${{ env.RELEASE_VERSION }}.tar.gz
          cd redis-${{ env.RELEASE_VERSION }}
          make CC=x86_64-w64-mingw32-gcc

      - name: Package Redis binaries
        run: |
          mkdir ${{ env.REDIS_DIST }}
          cp src/redis-server.exe src/redis-cli.exe ${{ env.REDIS_DIST }}
          tar -czvf ${{ env.REDIS_DIST }}.tar.gz ${{ env.REDIS_DIST }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: redis-windows
          path: ${{ env.REDIS_DIST }}.tar.gz

      - name: Calculate the hash value
        run: |
          'Hashes' | Out-File -Append .\redis_latest_body.txt
          '=========' | Out-File -Append .\redis_latest_body.txt
          Get-FileHash .\${{ env.REDIS_DIST }}.tar.gz | Format-List
          Get-FileHash .\${{ env.REDIS_DIST }}.tar.gz | Format-List | Out-File -Append .\redis_latest_body.txt

      - name: Add from workflow
        run: |
          "From workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" | Out-File -Append .\redis_latest_body.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Redis ${{ env.RELEASE_VERSION }} for Windows
          tag_name: ${{ env.RELEASE_VERSION }}
          body_path: redis_latest_body.txt
          make_latest: ${{ inputs.make_latest }}
          files: ${{ env.REDIS_DIST }}.tar.gz
